#!/usr/bin/env bash

cd /tmp
sudo rm -rf elixir-ls ~/util/base_util/lsp

git clone https://github.com/JakeBecker/elixir-ls.git
cd elixir-ls

mix deps.get
mix compile
mix elixir_ls.release -o ~/util/base_util/lsp
