---

# install java8

- name: java8 | add PPA
  apt_repository: repo=ppa:webupd8team/java state=present

- name: java8 | auto select the Oracle License
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
  changed_when: false

- name: java8 | remove openjdk-7-jre
  apt: pkg=openjdk-7-jre state=absent

- name: java8 | remove java7
  apt: pkg=oracle-java7-installer state=absent

- name: java8 | install
  apt: pkg=oracle-java8-installer state=latest 

