---
- name: update the apt repository 
  apt:  update_cache=yes cache_valid_time=3600   # 3600 seconds = 1 hour
  sudo: true
  
- name: install aptitude
  apt:  pkg=aptitude state=latest
  sudo: true

- name: upgrade apt packages
  apt:  upgrade=yes
  sudo: true

