---
# install virtual_box
# see https://www.virtualbox.org/wiki/Linux_Downloads

- name: virtual_box | add apt key
  sudo: true
  apt_key: url=http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc state=present

- name: virtual_box | add repository
  sudo: true
  apt_repository: repo='deb http://download.virtualbox.org/virtualbox/debian trusty contrib' state=present

- name: virtual_box | install package
  sudo: true
  apt: pkg=virtualbox-4.3 state=latest
