---
- name: update the apt repository 
  apt:  update_cache=yes cache_valid_time=3600   # 3600 seconds = 1 hour
  sudo: true

- name: upgrade apt packages
  apt:  upgrade=yes
  sudo: true

- name: install base packages
  sudo: true
  apt:  pkg=$item state=latest install_recommends=no
  with_items:
    - build-essential
    - curl                      
    - dnsutils                  
    - dstat                     
    - encfs                     
    - git-core                  
    - htop                      
    - iftop                     
    - libmagickcore-dev         
    - libmagickwand-dev         
    - graphviz                  
    - imagemagick               
    - iotop                     
    - libcurl4-openssl-dev
    - libevent-dev              
    - libncurses5-dev           
    - libreadline-dev
    - libssl-dev
    - libxml2-dev               
    - libxslt1-dev
    - multitail                 
    - python-software-properties
    - sshfs                     
    - tree                      
    - unison                    
    - wget                      
    - wkhtmltopdf               
    - xvfb                      
    - zip                       
    - zlib1g-dev
    - exuberant-ctags
    - vim-gnome

- name: upload lang.sh
  copy: src=lang.sh dest=/etc/profile.d/lang.sh
  sudo: true
