---
- name: cli_base | install base packages
  sudo: true
  apt:  pkg={{item}} state=latest install_recommends=no
  with_items:
    - python-software-properties
    - build-essential
    - dnsutils                  
    - git-core                  
    - libmagickcore-dev         
    - libmagickwand-dev         
    - imagemagick               
    - graphviz                  
    - htop                      
    - atop
    - ncdu
    - nmon
    - iftop                     
    - dstat                     
    - iotop                     
    - nload
    - sysstat
    - libcurl4-openssl-dev
    - libevent-dev              
    - libncurses5-dev           
    - libreadline-dev
    - libssl-dev
    - libxml2-dev               
    - libxslt1-dev
    - wkhtmltopdf               
    - multitail                 
    - unison                    
    - encfs                     
    - sshfs                     
    - xvfb                      
    - tree                      
    - curl                      
    - wget                      
    - zip                       
    - zlib1g-dev
    - exuberant-ctags
    - vim-gnome
    - ruby1.9.1

- name: cli_base | upload lang.sh
  copy: src=lang.sh dest=/etc/profile.d/lang.sh
  sudo: true
