---
- name: ruby-install | get package
  sudo: no
  get_url:
    url: https://github.com/postmodern/ruby-install/archive/v{{ruby_install_version}}.tar.gz
    dest: /tmp/ruby-install-{{ruby_install_version}}.tar.gz
    force: no

- name: ruby-install | untar package
  sudo: no
  shell: tar -xzf /tmp/ruby-install-{{ruby_install_version}}.tar.gz chdir=/tmp creates=/tmp/ruby-install-{{ruby_install_version}}

- name: ruby-install | install
  sudo: yes
  command: make install chdir=/tmp/ruby-install-{{ruby_install_version}} creates=/usr/local/bin/ruby-install

# - name: ruby-install | build {{ruby}}
#   sudo: no
#   shell: /usr/local/bin/ruby-install {{ruby}} creates=~/.rubies/{{ruby.replace(' ','-')}}
#   when: ruby is defined
