---
- name: ruby-install | get package
  sudo: no
  get_url:
    url: https://github.com/postmodern/ruby-install/archive/v{{ruby_install_version}}.tar.gz
    dest: /tmp/ruby-install-{{ruby_install_version}}.tar.gz
    force: no

- name: ruby-install | untar package
  sudo: no
  shell: tar -xzf /tmp/ruby-install-{{ruby_install_version}}.tar.gz chdir=/tmp creates=/tmp/ruby-install-{{ruby_install_version}}

- name: ruby-install | install script
  sudo: yes
  command: make install chdir=/tmp/ruby-install-{{ruby_install_version}} creates=/usr/local/bin/ruby-install

- name: ruby-install | build rubies
  sudo: no
  shell: /usr/local/bin/ruby-install ruby {{item}} creates=~/.rubies/ruby-{{item}}
  with_items: chruby_rubies

- name: ruby-install | set global ruby
  sudo: no
  shell: echo {{chruby_global}} > ~/.ruby-version
  changed_when: false

- name: ruby-install | setup rbenv symlink directory
  file: path=/home/{{rem_user}}/.rbenv state=directory

- name: ruby-install | create rbenv symlink (for RubyMine support)
  file: src=/home/{{rem_user}}/.rubies dest=/home/{{rem_user}}/.rbenv/versions state=link 
