---
- hosts: mego
  sudo:  true
  vars:
    - roles_dir:    ~/.ansible_playbooks/roles
    - lcl_user:     aleak
    - rem_user:     aleak
    - src_root:     /home/{{lcl_user}}/lr/X440
  roles:
    - "{{roles_dir}}/dotfile"
    - "{{roles_dir}}/visudo"
    - "{{roles_dir}}/cli_base"
    - "{{roles_dir}}/cli_user" 

- hosts: mego
  user:  aleak
  vars:
    - roles_dir: ~/.ansible_playbooks/roles
    - user:      aleak
    - pg_user:   x440 
    - pg_pass:   ${POSTGRES_PASS}
  roles:
    - "{{roles_dir}}/cli_util"
    - "{{roles_dir}}/postgres"
    - "{{roles_dir}}/postgres_user" 
    # - {{roles_dir}}/nginx
    # - {{roles_dir}}/redis
    - "{{roles_dir}}/memcached"
    - "{{roles_dir}}/rbgems"
    - "{{roles_dir}}/gui_base"
    - "{{roles_dir}}/gui_util"
