---
- hosts: mego
  sudo:  true
  vars:
    - roles_dir:    ~/.ansible_playbooks/roles
    - lcl_user:     aleak
    - rem_user:     aleak
    - src_root:     /home/{{lcl_user}}/lr/X440
    - dotfile:      ${src_root}/.rbenv-vars-private
    - rbenv_root:   /home/{{rem_user}}/.rbenv
    - rbenv_vers:   ${rbenv_root}/versions
    - rbenv_cmd:    ${rbenv_root}/bin/rbenv
    - rbenv_global: 2.0.0-p247
    - rbenv_rubies: 
        - 2.0.0-p247
  roles:
    - ${roles_dir}/dotfile
    - ${roles_dir}/visudo
    - ${roles_dir}/cli_base
    - ${roles_dir}/cli_user 
    - ${roles_dir}/rbenv

- hosts: mego
  user:  aleak
  vars:
    - roles_dir: ~/.ansible_playbooks/roles
    - user:      aleak
    - pg_user:   x440 
    - pg_pass:   ${POSTGRES_PASS}
  roles:
    - ${roles_dir}/cli_util
    - ${roles_dir}/postgres
    - ${roles_dir}/postgres_user 
    # - ${roles_dir}/nginx
    # - ${roles_dir}/redis
    - ${roles_dir}/memcached
    - ${roles_dir}/rbgems
    - ${roles_dir}/gui_base
    - ${roles_dir}/gui_util
