---

# install docker
# see http://docs.docker.io/en/latest/installation/ubuntulinux/

- hosts: hosts-new
  gather_facts: no
  sudo: true
  tasks:
    - name: install the backported kernel
      apt:  pkg=linux-image-generic-lts-raring state=present
      register: kernel_status
    - name: reboot
      when: kernel_status.changed == "False"
      command: /sbin/reboot 
    - name: wait for the machine to reboot
      local_action: wait_for port=22 delay=20 timeout=300
      sudo: false
      when: kernel_status.changed == "False"
    - name: add docker PPA
      apt_repository: repo=ppa:dotcloud/lxc-docker state=present
    - name: update the apt cache
      apt:  update-cache=true
    - name: install docker
      apt:  pkg=lxc-docker state=present update-cache=true
