---
# first:
# - install ubuntu
# - sudo apt-get install ssh
# - from old: keysend <newsys> <passwd>
# - visudo
# then run: ansible_playbook gui64.yml
# then run from new: keysend fils <passwd>
- vars:
    - rem_host:     gui64
    - rem_user:     aleak 
    - lcl_user:     aleak                            
    - roles_dir:    ~/.ansible_playbooks/roles       
    - lcl_root:     "/home/{{lcl_user}}/lr/X440"       
    - dotfile:      "{{lcl_root}}/.env"
    - pg_user:      "{{APP_NAME}}"
    - pg_pass:      "{{POSTGRES_PASS}}"
    - pg_dbs:
        - "{{pg_user}}_production"
        - "{{pg_user}}_test"
        - "{{pg_user}}_development"
    - chruby_global: 2.1.2
    - chruby_rubies:
        2.1.2
  remote_user: "{{rem_user}}"
  hosts:       "{{rem_host}}"
  sudo: true
  roles:
    - "{{roles_dir}}/dotdeb"
    - "{{roles_dir}}/cli_base"
    - "{{roles_dir}}/cli_util"
    - "{{roles_dir}}/chruby"
    - "{{roles_dir}}/ruby-install"
    - "{{roles_dir}}/ruby_gems"
    - "{{roles_dir}}/postgres"
    - "{{roles_dir}}/postgres_user"
    - "{{roles_dir}}/postgres_db"  
    - "{{roles_dir}}/nginx"
    - "{{roles_dir}}/redis"
    - "{{roles_dir}}/memcached"
    - "{{roles_dir}}/gui_base"
    - "{{roles_dir}}/gui_util"
    - "{{roles_dir}}/gui_config"
    - "{{roles_dir}}/ansible"
    - "{{roles_dir}}/docker"
    - "{{roles_dir}}/virtual_box"
    - "{{roles_dir}}/vagrant"
    - "{{roles_dir}}/chrome"

