---
- hosts: hosts-new
  vars:
    - tgt_user:     aleak 
    - rbenv_root:   /home/${tgt_user}/.rbenv
    - ruby_version: 2.0.0-p195
  tasks:
    - name: rbenv | update rbenv repo
      sudo: false
      git:  repo=git://github.com/sstephenson/rbenv.git dest=$rbenv_root version=v0.4.0
    - name: rbenv | install ruby-build
      sudo: false
      git:  repo=git://github.com/sstephenson/ruby-build.git dest=${rbenv_root}/plugins/ruby-build
    - name: rbenv | install ruby $ruby_version
      sudo: false
      shell: RBENV_ROOT=${rbenv_root} rbenv install $ruby_version
    - name: rbenv | set global ruby $ruby_version
      sudo: false
      shell: RBENV_ROOT=${rbenv_root} rbenv global $ruby_version
      when_failed: $ruby_installed
    - name: rbenv | rehash
      sudo: false
      shell: RBENV_ROOT=${rbenv_root} rbenv rehash
      when_failed: $ruby_installed
