---

# install docker
# see http://docs.docker.io/en/latest/installation/ubuntulinux/

- name: docker | install docker
  apt:  pkg=docker.io state=latest

- name: docker | setup executable symlink
  sudo: true
  file: src=/usr/bin/docker.io dest=/usr/local/bin/docker state=link


