---
# see http://wiki.postgresql.org/wiki/Apt
# see http://wiki.postgresql.org/wiki/Apt/FAQ
- name: postgres | add postgres repository
  template: src=pgdg.list dest=/etc/apt/sources.list.d/pgdg.list
  sudo: true
  notify: 
    - apt-cache update
- name: postgres | import postgres repository key
  apt_key: url=http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc state=present
  sudo: true
  notify: 
    - apt-cache update
- name: postgres | remove old postgres versions
  sudo: true
  apt: pkg=$item state=absent purge=yes
  with_items:
    - postgresql
    - postgresql-9.1
- meta: flush_handlers
- name: postgres | install postgres packages
  sudo: true
  apt:  pkg=$item state=latest install_recommends=yes
  with_items:
    - libpq-dev 
    - python-psycopg2
    - postgresql-9.3
    - postgresql-contrib
    - pgadmin3
- name: postgres | security settings for user creation
  lineinfile: state=present dest=/etc/postgresql/9.3/main/pg_hba.conf regexp="^local +all +postgres +peer" line="local all postgres trust" backrefs=yes
  sudo: true
  notify:
    - restart postgres 
- name: postgres | security settings for database creation
  lineinfile: state=present dest=/etc/postgresql/9.3/main/pg_hba.conf regexp="^local +all +all +peer" line="local all all trust" backrefs=yes
  sudo: true
  notify:
    - restart postgres 
- meta: flush_handlers
- name: postgres | create template_base database
  postgresql_db: name=template_base encoding=UTF8 lc_collate=en_US.UTF-8 lc_ctype=en_US.UTF-8 template=template0
  sudo: true
# - name: postgres | create database
#   shell: psql -U postgres -c 'create database qwer'
#   sudo: true
