---
- name: gui_util | create a util directory
  file: path=/home/{{rem_user}}/util state=directory

- name: gui_util | install pdev_util for target user
  synchronize: src=/home/{{lcl_user}}/util/pdev_util dest=/home/{{rem_user}}/util

- name: gui_util | run util init script
  sudo: false
  shell: /home/{{rem_user}}/util/base_util/init creates=/home/{{rem_user}}/.gitconfig
